steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'VW Hack2Sol_cfdev2020'
      space: 'cicd'
