steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: '7d1682cbtrial'
      space: 'test'
